# Generated by Django 5.0 on 2023-12-31 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
