# Generated by Django 5.0 on 2024-01-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_product_pro_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
