# Generated by Django 5.0 on 2023-12-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_product_pro_stock2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_stock2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
