# Generated by Django 5.0 on 2023-12-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_product_pro_stock2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_stock2',
        ),
    ]
